export const ADD_RESTAURANTS = "ADD_RESTAURANTS";
export const START_LOADING_RESTAURANTS = "START_LOADING_RESTAURANTS";
export const SUCCESSFULLY_LOADED_RESTAURANTS = "SUCCESSFULLY_LOADED_RESTAURANTS";
export const FAILED_LOADING_RESTAURANTS = "FAILED_LOADING_RESTAURANTS";