//restaurants
export const ADD_RESTAURANTS = "ADD_RESTAURANTS";
export const START_LOADING_RESTAURANTS = "START_LOADING_RESTAURANTS";
export const SUCCESSFULLY_LOADED_RESTAURANTS = "SUCCESSFULLY_LOADED_RESTAURANTS";
export const FAILED_LOADING_RESTAURANTS = "FAILED_LOADING_RESTAURANTS";

//users
export const START_LOADING_USERS = "START_LOADING_USERS";
export const ADD_USERS = "ADD_USERS";
export const SUCCESSFULLY_LOADED_USERS = "SUCCESSFULLY_LOADED_USERS";

//events
export const START_LOADING_EVENTS = "START_LOADING_EVENTS";
export const ADD_EVENTS = "ADD_EVENTS";
export const SUCCESSFULLY_LOADED_EVENTS = "SUCCESSFULLY_LOADED_EVENTS";
export const ADD_EVENT = "ADD_EVENT";
export const START_EDITING_EVENT= "START_EDITING_EVENT";
export const SUCCESSFULLY_UPDATED_EVENT="SUCCESSFULLY_UPDATED_EVENT";

