//restaurants
export const ADD_RESTAURANTS = "ADD_RESTAURANTS";
export const START_LOADING_RESTAURANTS = "START_LOADING_RESTAURANTS";
export const SUCCESSFULLY_LOADED_RESTAURANTS = "SUCCESSFULLY_LOADED_RESTAURANTS";
export const FAILED_LOADING_RESTAURANTS = "FAILED_LOADING_RESTAURANTS";

//users
export const START_LOADING_USERS = "START_LOADING_USERS";
export const ADD_USERS = "ADD_USERS";
export const SUCCESSFULLY_LOADED_USERS = "SUCCESSFULLY_LOADED_USERS";

//events
export const START_LOADING_CREATED_EVENTS = "START_LOADING_CREATED_EVENTS";
export const SUCCESSFULLY_LOADED_CREATED_EVENTS = "SUCCESSFULLY_LOADED_CREATED_EVENTS";
export const SUCCESSFULLY_CREATED_EVENT = "SUCCESSFULLY_CREATED_EVENT";
